.github/workflows/CI.yml

Run with LTS 11+ JDKs for the former, stick to JDK 21 for the latter

Split compilation & test execution in CI

---

src/main/java/org/neo4j/importer/v1/ImportSpecificationDeserializer.java
src/main/java/org/neo4j/importer/v1/graph/CycleDetector.java
src/main/java/org/neo4j/importer/v1/validation/SpecificationValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDependencyCycleValidator.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerExtraValidationTest.java
src/test/java/org/neo4j/importer/v1/graph/CycleDetectorTest.java

Do not report cycle errors if any start/end node refs are dangling

Include start/end node ref to cycle detection

---

src/main/java/org/neo4j/importer/v1/actions/Action.java
src/main/java/org/neo4j/importer/v1/actions/ActionType.java
src/main/java/org/neo4j/importer/v1/actions/BigQueryAction.java
src/main/java/org/neo4j/importer/v1/actions/CypherAction.java
src/main/resources/spec.v1.0.json
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerActionTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerSourceTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationTest.java
src/test/java/org/neo4j/importer/v1/actions/ActionTest.java

- add missing `BigQuery` action
- add validation tests for actions

feat: add validation for actions

---

src/main/java/org/neo4j/importer/v1/ImportSpecification.java
src/main/java/org/neo4j/importer/v1/ImportSpecificationDeserializer.java
src/main/resources/spec.v1.json
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerActionTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerExtraValidationTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerSourceTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerTest.java
src/test/java/org/neo4j/importer/v1/ImportSpecificationTest.java
src/test/resources/e2e/admin-import/spec.json
src/test/resources/e2e/admin-import/spec.yaml
src/test/resources/e2e/beam-import/spec.json
src/test/resources/e2e/beam-import/spec.yaml

Introduce mandatory version to the spec.

feat: add version to spec, limit version to major

---

src/main/java/org/neo4j/importer/v1/targets/Constraint.java
src/main/java/org/neo4j/importer/v1/targets/NodeConstraint.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipSchema.java

This is useful to centralize some Dataflow mapping code

fix: make node constraint super classes visible

---

src/main/java/org/neo4j/importer/v1/targets/SourceTransformations.java

This avoid null checks on the client side.

feat: make aggregations easier to work with

---

src/main/java/org/neo4j/importer/v1/targets/EntityTarget.java
src/main/java/org/neo4j/importer/v1/targets/NodeSchema.java
src/main/java/org/neo4j/importer/v1/targets/NodeTarget.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipSchema.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipTarget.java
src/test/java/org/neo4j/importer/v1/targets/NodeTargetTest.java
src/test/java/org/neo4j/importer/v1/targets/RelationshipTargetTest.java

This resolves all the properties that are part of key constraints
or unique/existence constraints.

feat: introduce key properties API via new supertype for node/rels

---

src/main/java/org/neo4j/importer/v1/targets/NodeSchema.java
src/main/java/org/neo4j/importer/v1/targets/NodeTarget.java
src/main/java/org/neo4j/importer/v1/targets/NodeTypeConstraint.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipSchema.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipTarget.java
src/main/java/org/neo4j/importer/v1/targets/RelationshipTypeConstraint.java
src/main/resources/spec.v1.json
src/test/java/org/neo4j/importer/v1/e2e/AdminImportIT.java
src/test/java/org/neo4j/importer/v1/e2e/BeamIT.java
src/test/java/org/neo4j/importer/v1/targets/NodeTargetTest.java
src/test/java/org/neo4j/importer/v1/targets/RelationshipTargetTest.java
src/test/java/org/neo4j/importer/v1/targets/TargetTest.java

Simplify naming and make the label selection for node type constraints explicit.

feat: make type constraints more explicit & consistent

---

src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingLabelInTypeConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInTypeConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoUntypedPropertyInTypeConstraintValidator.java
src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator

This will align all dangling validators in a much more readable way.

refactor: simplify of dangling validators

---

pom.xml

Fix warning of deprecated sortpom setting.

build: remove sortpom warning

---

src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingLabelInExistenceConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingLabelInKeyConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingLabelInUniqueConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInExistenceConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInKeyConstraintValidator.java
src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInUniqueConstraintValidator.java

This makes every error code unique per validator.

fix: error code clashes

---

pom.xml

Better late than never, right? 😅

fix: update project description

---

.teamcity/settings.kts

This PR updates Kotlin DSL version for TeamCity.

ci: update version

---

src/main/java/org/neo4j/importer/v1/validation/plugin/NoDuplicatedLabelInFullTextIndexValidator.java
src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerNodeTargetTest.java

[Trello](https://trello.com/c/hrABkRid/558-disallow-duplicate-labels-in-fulltext-index-definitions)
Disallow duplicate labels in full text index target node definitions

feat: add validator for full text index duplicate labels

---

examples/apache-beam/src/test/java/org/neo4j/importer/BeamExampleIT.java
examples/apache-beam/src/test/resources/specs/dvd_rental.yaml

feat: add support for schema init + fix data conversion

---

examples/neo4j-admin/src/test/java/org/neo4j/importer/Neo4jAdminExampleIT.java

chore: just a few minor changes

---

README.md

docs: fix links after multimodule restructuring

---

jreleaser.yml

Align generated tag names with the existing ones.

ci: fix tag name

---

core/src/main/java/org/neo4j/importer/v1/pipeline/NodeTargetStep.java
core/src/main/java/org/neo4j/importer/v1/pipeline/RelationshipTargetStep.java
core/src/main/java/org/neo4j/importer/v1/targets/NodeSchema.java
core/src/main/java/org/neo4j/importer/v1/targets/RelationshipSchema.java
core/src/main/java/org/neo4j/importer/v1/targets/RelationshipTarget.java
core/src/main/java/org/neo4j/importer/v1/validation/Neo4jDistributionValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInExistenceConstraintValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInFullTextIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInKeyConstraintValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInPointIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInRangeIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInTextIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInTypeConstraintValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInUniqueConstraintValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDanglingPropertyInVectorIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyAndExistenceConstraintsValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyAndUniqueConstraintsValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyConstraintAndRangeIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantUniqueConstraintAndRangeIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoUntypedPropertyInTypeConstraintValidator.java
core/src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerExtraValidationTest.java
examples/neo4j-admin/src/test/java/org/neo4j/importer/Neo4jAdminExampleIT.java

Only node properties were covered until now.

fix: make sure rel type constraints refer to typed properties

---

core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoDuplicatedSchemaNameValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyAndExistenceConstraintsValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyAndUniqueConstraintsValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantKeyConstraintAndRangeIndexValidator.java
core/src/main/java/org/neo4j/importer/v1/validation/plugin/NoRedundantUniqueConstraintAndRangeIndexValidator.java
core/src/main/resources/META-INF/services/org.neo4j.importer.v1.validation.SpecificationValidator
core/src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerExtraValidationTest.java
core/src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerNeo4jVersionValidationTest.java
core/src/test/java/org/neo4j/importer/v1/ImportSpecificationDeserializerRelationshipTargetTest.java
core/src/test/resources/e2e/admin-import/spec.json
core/src/test/resources/e2e/admin-import/spec.yaml
core/src/test/resources/e2e/beam-import/spec.json
core/src/test/resources/e2e/beam-import/spec.yaml

This PR adds a new validator plugin which checks that every index and constraint use a unique name.

feat: ensure each constraint and index have unique names
